### ISSUE TITLE
Payment calculation

### ISSUE THREAD

**Issue by cliff67** [TratokToken/smart-contracts#31]
I offered a room  for 500 TRAT a night. Wenn offering the room, there was no Information about the commisson for Tratok - should be stated.
When I book this room, it shows total cost 2000 (okay. 4 x 500) - But why is there a rebate of 70 TRAT that has nowhere been offered. A discount must be shown - if there is any rebate, this has to be propagated intensively as something Special!!!
When someone books for 2000 TRAT he is prepared to pay it - so no rebate later on. Do it in Advance...

Furthermore it should be explained, what is meant by rebate reward.

**Comment by cliff67** [comment]
The contact link on  the booking statement  does not work.

**Comment by TratokToken** [comment]
The commission and rebate terms will be fully detailed in the agreements given to those who list their properties. At the moment, since testing, and not live there is no point in making beta testers agree to these terms with fictional properties.

The contact link has been updated. Thanks for finding this bug.
